title: MinaeJeon
published: true
description: Just another documentation theme compatible with GitHub Pages
name: minae_jeon
url: "https://minaejeon.github.io/"
theme: null
futrue: true

# debug:
#   compress: true
#   dist: false
#   shortcodes: true
futrue: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
